### ISSUE TITLE
Fix page order (A Variorum Story of the Stone)

### ISSUE THREAD

**Issue by gigamorph** [yale-web-technologies/mirador-project#13]
From @proftina

Page 6B of Chapter 5 does not belong there. It is not 6B but 9B (The 6B1 is in fact 6B and it is also in the right place). And after 9A there is no 9B. So can we put the 9B in the right place?

**Comment by gigamorph** [comment]
Done. Waiting for feedback.

**Comment by ProfTina** [comment]
Fixed!  Thank you!

On Tue, May 31, 2016 at 11:59 AM, Seong-June Kim notifications@github.com
wrote:

> Done. Waiting for feedback.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/yale-web-technologies/mirador-project/issues/13#issuecomment-222735070,
> or mute the thread
> https://github.com/notifications/unsubscribe/ARetKxXO1OTXONaq4eCUQT6qGRjF4yCZks5qHFrzgaJpZM4IqgWh
> .

## 

Tina Lu
Professor of Chinese Literature
Dept. of East Asian Languages and Literatures
Yale University
P.O. Box 208236
New Haven, CT 06520-8236
