### ISSUE TITLE
Create keyboard command to navigate through annotations

### ISSUE THREAD

**Issue by dcheather** [yale-web-technologies/mirador-project#133]
Create the ability to use a keyboard command, such as tab or down arrow, to move from one annotation entry to another with the same effect as clicking on that entry. This was as a user is reading they can move through entries and have the highlights in other annotation windows activate as well as the outlines in the panel.

On a side note, this would account for a major accessibility issue going forward.

**Comment by gigamorph** [comment]
ETA: 6/30/2017

**Comment by gigamorph** [comment]
Done
