### ISSUE TITLE
Adjust CSS for annotation windows

### ISSUE THREAD

**Issue by dcheather** [yale-web-technologies/mirador-project#134]
I'll post the CSS changes here once I get a chance to finalize them.

**Comment by gigamorph** [comment]
ETA: 6/2/2017

**Comment by dcheather** [comment]
Here is the first set of changes. In staging there is no longer a "chapter" bar. Is that staying?

.ym_annotation_window.fixed_height_cells .annowin_anno > .normal_view {     	
/* height: 100px; */     	
/* overflow-y: scroll; */
}


.annowin_anno { 	background-color: #fafafa;
border: solid 2px #fafafa; 	
color: #000;
/* padding: 3px; */
}

.ym_anno_selected {
border-color: #4684cc;
border-width: 1px;
padding: 0;
}

**Comment by gigamorph** [comment]
Yes, it is staying. I think it's a data entry problem on the staging annotation server. You may want to look at the production application for reference.

**Comment by dcheather** [comment]
Also this:

.annowin_anno .content {     	padding: 5px 10px 5px 15px;
	font-size: 14px;
	width: 100%;
}

**Comment by gigamorph** [comment]
Deployed to staging. 

It seems the highlight border is too thin at 1px and barely noticeable. It becomes worse for Ten Thousand Rooms where there are fewer annotations and no chapter/scene headers.

**Comment by dcheather** [comment]
You are right, it does look too thin. Here are some adjustments:

I have not seen the hover before, but this change will keep it from re-arranging the text.
.annowin_anno:hover {
    /* border: solid 1px #bbb; */
    border-color: #bbb;
}

.ym_anno_selected {
border-color: #4684cc;
border-width: 2px;
padding: 0;
}

**Comment by gigamorph** [comment]
Done.
