### ISSUE TITLE
Add tool tips to the panel arrows in Mirador

### ISSUE THREAD

**Issue by dcheather** [yale-web-technologies/mirador-project#135]
Add in a "Next Panel" "Previous Panel" tool tip to the panel arrows in Mirador.

**Comment by gigamorph** [comment]
ETA: 6/2/2017

**Comment by gigamorph** [comment]
Done. Deployed to staging.

**Comment by dcheather** [comment]
Can these show quicker? I feel that people will click on it before the tool tip is visible.

**Comment by gigamorph** [comment]
I'm afraid it's browser dependent because I'm just using the "title" attribute of the element.
