### ISSUE TITLE
Create one to one relationship for annotation entries

### ISSUE THREAD

**Issue by dcheather** [yale-web-technologies/mirador-project#137]
Ideal solution, create a one to one relationship between related annotations in different window. When one is clicked in one window instead of highlighting the entire scene, it only highlights the directly related cell.

Other solution, change the border highlight to the scene level and not the individual entry level.

**Comment by gigamorph** [comment]
ETA: 6/30/2017

**Comment by gigamorph** [comment]
I have deployed a makeshift version. It just assumes all layers have the same structure, which is the case for "Sun of Faith Tibetan" and "Sun of Faith English". It should already look much better than the previous version but it's not a complete fix, for which I'm still waiting on the tag updates from the backend.

**Comment by gigamorph** [comment]
Done.

**Comment by dcheather** [comment]
When you select an english annotation, the corresponding Tibetan entry moves to the top and is partially blocked from view. 

![image](https://user-images.githubusercontent.com/15327010/28879863-4156f690-7771-11e7-8672-cd4c362da52f.png)
