### ISSUE TITLE
Add table of contents to left tray in Mirador

### ISSUE THREAD

**Issue by dcheather** [yale-web-technologies/mirador-project#139]
Create a TOC like the one on the drupal site in the left tray in Mirador. These will open the English text anchored (not filtered) to the requested chapter.

**Comment by gigamorph** [comment]
ETA: 7/7/2017

**Comment by gigamorph** [comment]
Done. The "open the English text" part is not implemented but it is more closely related to https://github.com/yale-web-technologies/mirador-project/issues/141 so I'll deal with it there.
