### ISSUE TITLE
Link Tibetan in TOC to Tibetan annotation window

### ISSUE THREAD

**Issue by dcheather** [yale-web-technologies/mirador-project#140]
If possible, link the Tibetan translation of the chapter in the table of contents to the Tibetan annotation window.

**Comment by gigamorph** [comment]
ETA: 7/7/2017

NOTE: this feature may not turn out to be feasible though. Will update.

**Comment by gigamorph** [comment]
I still don't think we should do this.

**Comment by dcheather** [comment]
This was a nice to have. You can skip it.

**Comment by gigamorph** [comment]
Not implemented. Closing.
