### ISSUE TITLE
Don't open the Chapter or Scene annotation windows

### ISSUE THREAD

**Issue by dcheather** [yale-web-technologies/mirador-project#141]
No longer launch the chapter or scene annotation windows unless specifically selected in the annotation drop-down menu.

Added by Seong: also open the "English" layer by default when no annotation windows are already open.

**Comment by gigamorph** [comment]
ETA: 7/7/2017

**Comment by gigamorph** [comment]
Done and deployed.

**Comment by dcheather** [comment]
The TOC should open the English text. It isn't opening anything at the moment.
