### ISSUE TITLE
Add tool tip to panel viewer icon

### ISSUE THREAD

**Issue by dcheather** [yale-web-technologies/mirador-project#142]
On the bottom of Mirador window, add a tool tip to the ellipses icon "View All Panels"

**Comment by gigamorph** [comment]
ETA: 6/2/2017

**Comment by gigamorph** [comment]
@dcheather Actually we need another tooltip when the bottom panel is shown, and "Hide All Panels" won't do. 

Can we use something like "Toggle panel selector" in both cases, or "Show panel selector" and "Hide panel selector" for each? And should I capitalize all words?

**Comment by dcheather** [comment]
I think selector sounds a bit too technical. Let me get back to you on this one.

**Comment by dcheather** [comment]
How about just "View Panels" and "Hide Panels"

**Comment by gigamorph** [comment]
Done.
