### ISSUE TITLE
Sticky chapter and scene bars

### ISSUE THREAD

**Issue by dcheather** [yale-web-technologies/mirador-project#144]
Option 1. Have the bar for chapters and scenes in the annotation windows stay at the top until the next bar reaches the top, then that becomes the sticky bar.

Option 2. Have some notation of which chapter and scene you are in at the top of the annotation window.

**Comment by gigamorph** [comment]
ETA: 6/23/2017

**Comment by dcheather** [comment]
For an example, the dividing bars in outlook for the email frame. "Today" "Saturday" "Friday" etc.. they are sticky until the next on gets to the top then it is sticky.

**Comment by gigamorph** [comment]
It is a hard problem because I've never done it anything like this before. It may turn out easier than I think but it's still a big risk compared with what we might gain. I'll probably try this after all other issues are resolved.

**Comment by dcheather** [comment]
I think if the other larger tickets get implemented this may not be an issue. It's also something we can test in usability testing to see if the users even need it. It came from the discussion that users don't know where they are in the text. This is easy to do user testing on.

**Comment by gigamorph** [comment]
Done. Headers are sticky now.
