### ISSUE TITLE
Annotation window sync

### ISSUE THREAD

**Issue by dcheather** [yale-web-technologies/mirador-project#145]
If possible, have the annotation windows sync up location to location of related entries. So as you move through one window, the other windows moves with it.

**Comment by gigamorph** [comment]
ETA: 6/30/2017

**Comment by gigamorph** [comment]
@dcheather I think we had agreed that this feature wasn't really feasible and sync'ing by clicking would be good enough, but my memory is hazy. Could you confirm?

**Comment by dcheather** [comment]
By moving I meant in relation to ticket #133. So not scrolling, but as the user moves through the text however you implement it for that ticket.

**Comment by gigamorph** [comment]
Done
