### ISSUE TITLE
Natural language text in image overlays

### ISSUE THREAD

**Issue by dcheather** [yale-web-technologies/mirador-project#146]
Change out the text in the image overlays so they are natural language. Ex. "Chapter 1" "Chapter 1, Scene 2" etc. Basically get rid of the ones that look like markup.

**Comment by gigamorph** [comment]
ETA: 7/7/2017

**Comment by dcheather** [comment]
The Panel notation in the overlay is less important than Chapter & Scene. Not sure how you plan on doing this. Can you either remove the Panel information from the link or make sure the Scene number is fully visible?

![image](https://user-images.githubusercontent.com/15327010/28573769-aaa46348-7119-11e7-8a99-9efd312e5f77.png)

**Comment by gigamorph** [comment]
I think we agreed an the format "Chapter 20, Scene 1". It's easy to change.

**Comment by gigamorph** [comment]
Done
