### ISSUE TITLE
Links in image overlays go to english text

### ISSUE THREAD

**Issue by dcheather** [yale-web-technologies/mirador-project#147]
Change the links from the image overlays to go to the English translation and not the generic chapter or scene annotation lists.

**Comment by gigamorph** [comment]
ETA: 6/30/2017

**Comment by gigamorph** [comment]
Done and deployed.

**Comment by dcheather** [comment]
This is still opening the scene list annotation window as well as the english text.

**Comment by gigamorph** [comment]
Sorry, somehow a setting had regressed to an invalid value. It should be fine now.
