### ISSUE TITLE
Chapter bar vs Scene Bar

### ISSUE THREAD

**Issue by dcheather** [yale-web-technologies/mirador-project#153]
Is it possible to generate a different class for a chapter header black bar vs a scene header bar? If so, can you add that so they can be styled separately.

**Comment by gigamorph** [comment]
Yes, it's possible.

**Comment by gigamorph** [comment]
Deployed to staging - http://life-of-the-buddha-rails-stg.herokuapp.com/

See chapter 25 and below for chapter headers. Also, there are headers for panels too, now that we are showing data for all panels in a single window. 

The classes I added are:
- page-header (for panels)
- header-level-1 (for chapters)
- header-level-2 (for scenes)
