### ISSUE TITLE
Let's try a new bg color for the chapter/scene headers

### ISSUE THREAD

**Issue by dcheather** [yale-web-technologies/mirador-project#159]
I think the highlight border is getting lost on some of the other annotation windows. I think this is an easy fix since you added in the new class for me. Just to check, that new class is only for LOTB, and won't affect ten thousand Rooms?

Can we try:

header-level-2 {
    background-color: #dddddd;
    color: #000000;
}

I think that less contrast will make it easier to read in general. So this may end up being a good thing.

**Comment by gigamorph** [comment]
I've updated staging with the new style.

**Comment by dcheather** [comment]
Looks great. The highlight definitely is more visible now. Lets get feedback on this from Andy and Kurtis today before closing.
