### ISSUE TITLE
Chapter 6 annotations are out of order

### ISSUE THREAD

**Issue by dcheather** [yale-web-technologies/mirador-project#162]
For Chapter 6, the scenes are out of order.

**Comment by dcheather** [comment]
This is only happening in Chrome.

**Comment by dcheather** [comment]
![image](https://user-images.githubusercontent.com/15327010/29830911-8683e14c-8cb1-11e7-8ac1-4a67e45fcce1.png)
![image](https://user-images.githubusercontent.com/15327010/29830936-99b1fa42-8cb1-11e7-9a60-6635d56139ea.png)

**Comment by gigamorph** [comment]
Should be fixed now. Please check.

**Comment by dcheather** [comment]
Looks good.
