### ISSUE TITLE
Annotation drawing tools/interface

### ISSUE THREAD

**Issue by Quintman** [yale-web-technologies/mirador-project#20]
Hi guys. Some questions about the drawing interface/tools after meeting with Mark Saba.
1. Is it possible to add a way to select line thickness?
2. Is there a way to draw using bezier curves (like you can do in Illustrator/Photoshop? I know this is a long shot, but Mark asked. This gives a much smoother line render. But as it is, the freehand tool makes a very jagged line.

**Comment by gigamorph** [comment]
Closing the issue because we have now imported the curves from Mark's Illustrator works. Regarding the line thickness, we haven't yet found way to control it.
