### ISSUE TITLE
Alternate image annotation method

### ISSUE THREAD

**Issue by Quintman** [yale-web-technologies/mirador-project#21]
After talking with Mark Saba, we wonder if the possible workflow would be possible.

We discussed importing annotation coordinates into Mirador from Photoshop/Illustrator. The problem seemed to be that Mirador creates a unique identifier for each annotation drawing.

But what if Mark creates a panel image with all the outlines drawn. This is imported into Mirador. Then he traces all the outlines to create image annotations. Then the background image is swapped out for a "clean" version (without the outlines drawn in it). This would make Mark's process much simpler since he would do the more labor intensive work in a more sophisticated editing program.

**Comment by gigamorph** [comment]
Mark will create shapes with Illustrator and export the into SVG. Seong or Roy will create each shape manually first and then overwrite its SVG data with the one from Mark.

By the way, please also note the drawing tool in Mirador has improved so it draws smoother curves than before.
