### ISSUE TITLE
Controlling the order of the annotation list—still a problem

### ISSUE THREAD

**Issue by mickhunter** [yale-web-technologies/mirador-project#36]
So long as I'm working on a single page, it's possible to rearrange the order of annotation items using the up and down arrows and then save those changes. However, if I advance to another page and then come back to the first page, it reverts back to the original order. In other words, the changes are lost as soon as I leave the page.

**Comment by gigamorph** [comment]
I can't seem to reproduce the problem. Could you tell us which annotations you tried to move in which book/chapter/page? Thanks.

**Comment by mickhunter** [comment]
Hi Seong,

In my Collected Sayings of Confucius project, go to the first page of
chapter two. Then try switching the order of the second and third items,
clicking "save," advancing to the next page, and then coming back to the
first page. I've tried it about ten times and it still doesn't work.

Also, the high school student who's currently working on Tina's project is
having the same problem.

Thanks!

Mick

On Wed, Aug 10, 2016 at 9:54 AM, Seong-June Kim notifications@github.com
wrote:

> I can't seem to reproduce the problem. Could you tell us which annotations
> you tried to move in which book/chapter/page? Thanks.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_yale-2Dweb-2Dtechnologies_mirador-2Dproject_issues_36-23issuecomment-2D238873734&d=CwMCaQ&c=-dg2m7zWuuDZ0MUcV7Sdqw&r=sudeOR097V8hLJ9fVh5ULaU2pLk1DXhmd6V7NOU8CDo&m=aDGKYUUqT9gZTjolQNKkehDwb7tbOEglfn1HL9t0Sik&s=Orokn107dgOrL45Eyd2b0aFEpfRF67vnNrd25gYvvXQ&e=,
> or mute the thread
> https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AMCqz24sifwvLmGY8wD0dXuAp7pngV9Vks5qedgrgaJpZM4JhJbV&d=CwMCaQ&c=-dg2m7zWuuDZ0MUcV7Sdqw&r=sudeOR097V8hLJ9fVh5ULaU2pLk1DXhmd6V7NOU8CDo&m=aDGKYUUqT9gZTjolQNKkehDwb7tbOEglfn1HL9t0Sik&s=sWrOG9G3K_gw-e8XfroitCdRxZggWqrbmjF3SY_IRFo&e=
> .

## 

Michael Hunter (mick.hunter@yale.edu)
Department of East Asian Languages and Literatures
Yale University
P.O. Box 208236
New Haven, CT 06520-8236
(203) 432-7529 (office)

**Comment by gigamorph** [comment]
@rlechich could you take a look why the following doesn't seem to work?

For record, the client sent

```
{"canvas_id":"http://manifests.ydc2.yale.edu/canvas/KZJY02-001-jpg","layer_id":"http://ten-thousand-rooms.herokuapp.com/layers/5557c1c3-53d5-4af5-bfc8-990008826fcc","annotation_ids":["http://annotations.tenkr.yale.edu/annotations/83eaeae0-2a02-4cd6-ae3a-b72b97adbb18","http://annotations.tenkr.yale.edu/annotations/6e377152-0f5b-4c3d-acff-105664616fad","http://annotations.tenkr.yale.edu/annotations/d8fb2520-086a-4066-8f64-47f69941c4e7"]}
```

and received

```
{
  "list_id": "http://annotations.tenkr.yale.edu/lists/http://ten-thousand-rooms.herokuapp…af5-bfc8-990008826fcc_http://manifests.ydc2.yale.edu/canvas/KZJY02-001-jpg"
}
```

But the order hasn't changed.

**Comment by gigamorph** [comment]
This has been fixed, according to @rlechich .
