### ISSUE TITLE
Problem with annotations - duplicates, not loading at all, etc.

### ISSUE THREAD

**Issue by gigamorph** [yale-web-technologies/mirador-project#44]
User (@mickhunter) reported problems using Mirador at http://mirador.tenkr.yale.edu/mirador?manifest=19&room_id=2
1. For canvas `http://manifests.ydc2.yale.edu/canvas/KZJY00-001-jpg`, 
   1. There are duplicate annotations with ID `http://annotations.tenkr.yale.edu/annotations/215bc9b4-ca41-4467-a823-4440c420eb8e`.
   2. Re-ordering request for moving the second duplicate up the list comes back with "success" message for the list `http://lists.tenkr.yale.edu/lists/http://ten-thousand-rooms.herokuapp.com/l…af5-bfc8-990008826fcc_http://manifests.ydc2.yale.edu/canvas/KZJY00-001-jpg`, but in fact it is not reordered. It probably is caused by the duplicity.
2.  The 3rd page is not loading at all any annotations, gives error -- need more clarification from user.

**Comment by rlechich** [comment]
#1 should be resolved.
#2: cannot duplicate error; have asked Mick for clarification.
