### ISSUE TITLE
Cannot select/copy annotation text in viewing mode

### ISSUE THREAD

**Issue by mickhunter** [yale-web-technologies/mirador-project#46]
Currently, the only way to highlight and copy a piece of text is to open up the annotation item in editing mode. In other words, without clicking "edit" on an annotation item, it's impossible to select text with one's cursor. It might not seem like a big deal but it makes working with annotation items (copying/pasting, looking up words in electronic dictionaries, etc.) very frustrating.

Thanks!

Mick

**Comment by gigamorph** [comment]
Disabled "draggable" to enable copy and paste from the annotation views. Seems to work well on FireFox and Safari, but not in Chrome. Filed a bug report with Mirador core:
https://github.com/ProjectMirador/mirador/issues/1143

**Comment by gigamorph** [comment]
Fixed.
