### ISSUE TITLE
Roy look into the missing SVG

### ISSUE THREAD

**Issue by gigamorph** [yale-web-technologies/mirador-project#62]
From Lec's note.

Kongzi jiyu 孔子集語 no annotations, missing SVG for second page, text is there.

**Comment by lecmaj** [comment]
The annotations missing, 4 drown boxes and 4 transcription layers. 


![mick_screen shot](https://cloud.githubusercontent.com/assets/4039037/21268066/187f9862-c37b-11e6-9e60-a97bff240eaf.png)

**Comment by rlechich** [comment]
I think after we migrated the data for the Drupal site that Mick just re-entered these?

**Comment by gigamorph** [comment]
@rlechich  This issue was created a long time ago so I think it is the original one. Please close it if you know the problem has been resolved.
