### ISSUE TITLE
Load new SVG shapes for Panel 1

### ISSUE THREAD

**Issue by gigamorph** [yale-web-technologies/mirador-project#66]
SVG definitions are at https://github.com/yale-web-technologies/mirador-project/blob/master/life-of-the-buddha/SVGs_panel01_delta_20170120.txt

Please note that this set contains only shapes that have changed, so take cautions not to delete unchanged ones.

**Comment by gigamorph** [comment]
Reopening. Sorry, I meant panel 1, not panel 2.

**Comment by rlechich** [comment]
this is done and seems to look good
